export const ADD_PRODUCT_BASKET = 'ADD_PRODUCT_BASKET';
export const GET_NUMBERS_BASKET  = 'GET_NUMBERS_BASKET';
export const DELL_NUMBERS_BASKET  = 'DELL_PRODUCT_BASKET';
export const DELLALL_NUMBERS_BASKET  = 'DELLALL_PRODUCT_BASKET';
export const DELLALL  = 'DELLALL';